const constants = {
    SKILLS_FETCH: "SKILLS_FETCH",
    SKILLS_FETCH_CANCEL: "CANCEL_SKILLS_FETCH",
    SKILL_CONTENT_SHOW: "SKILL_CONTENT_SHOW",
    SKILL_CONTENT_HIDE: "SKILL_CONTENT_HIDE"
}

export default constants